version: '3.9'

services:
  postgres:
    container_name: postgres-container
    image: postgres:14.1-alpine
    ports:
      - 5432:5432
    env_file:
      - ./server/development.env
    volumes:
      - ../data/db:/var/lib/postgresql/data
